include:
  - oci://dockersamples/labspace-content-dev
  - ./compose.override.yaml

services:

  # This development service is used to sync the changes of
  # the project files into the project directory that is located
  # back on the host.
  sync-service:
    image: alpine
    command: tail -f /dev/null
    volumes:
      - $HOME/.labspace/project:/project
    develop:
      watch:
        - path: ./project
          action: sync
          target: /project
          initial_sync: true
